Testing Pure Functions
callstack-internal/onboarding-hurali pull request #12
Opened 2022-06-30 13:10 UTC by hurali97

This PR includes:
- test case for generate Image url by icon 
- test case for generate params
- configuration for github action to run unit test

2022-06-30 14:04 UTC, adamTrz requested changes

2022-06-30 14:04 UTC, adamTrz commented on __tests__/helpers/generateImageUrlByIcon.test.ts
> +  expect(generateImageUrlByIcon(icon)).toBe(generateImageUrlByIcon(icon));
This test does not make sense to me. Even if function returns "bananas" string or anything else the test will pass...

2022-06-30 14:04 UTC, adamTrz commented on __tests__/react-query/generateParams.test.ts
> +  expect(generateParams(params)).toEqual(generateParams(params));
Same here.

2022-06-30 14:13 UTC, hurali97 commented on __tests__/helpers/generateImageUrlByIcon.test.ts
> +  expect(generateImageUrlByIcon(icon)).toBe(generateImageUrlByIcon(icon));
So should I test it against the result? like if I pass icon = "foo" to the fn, should I test the resultant output by hardcoding it? like so:  
  expect(generateImageUrlByIcon("foo")).toBe("http://www.abc.com/foo.png");

2022-07-01 08:09 UTC, adamTrz approved these changes

2022-07-01 08:09 UTC, merged